### ISSUE TITLE
Estou usando em ms.alami.no

### ISSUE THREAD

**Issue by ricalamino** [guto-alves/loterias-api#1]
Estou usando os resultados da sua API em https://ms.alami.no . Um app feito em Svelte, AWS para brincar um pouco com os números da MegaSena.

**Comment by guto-alves** [comment]
Sensacional, acabei de ver lá rs, muito bom saber disso! Se eu puder ajudar em algo é só falar ou se tiver qualquer sugestão sinta-se à vontade até mesmo para enviar um PR.
