### ISSUE TITLE
+Milionaria

### ISSUE THREAD

**Issue by Jose82153** [guto-alves/loterias-api#13]
Boa Tarde!

Muita boa sua API de resultados.
Você irá atualizar para colocar a +Milionária?

Obrigado

**Comment by guto-alves** [comment]
Obrigado! @Jose82153  

Adicionada a loteria +Milionária, pode ser acessada agora com "maismilionaria":

https://loteriascaixa-api.herokuapp.com/api/maismilionaria
https://loteriascaixa-api.herokuapp.com/api/maismilionaria/67
https://loteriascaixa-api.herokuapp.com/api/maismilionaria/latest
