### ISSUE TITLE
API com erro

### ISSUE THREAD

**Issue by marciorossetti2016** [guto-alves/loterias-api#15]
Amigo, criei um app que consome sua API, e não está mais funcionando, tem previsão de retorno ou encerrou os serviço. Fiz app como exercício da minha faculdade.

**Comment by luanaraujopmw** [comment]
> Amigo, criei um app que consome sua API, e não está mais funcionando, tem previsão de retorno ou encerrou os serviço. Fiz app como exercício da minha faculdade.

O heroku não tem mais o plano gratuito. Acredito que por causa disso está fora do ar.

**Comment by gleitons** [comment]
Estava utilizando essa API também, infelizmente acredito que possa ser  por causa do heroku não ser mais gratuito como o colega disse.

**Comment by Mardoniosc** [comment]
Se alguem precisar eu subi a api neste endereço 

https://api-loteria.servicosmsc.com.br/swagger-ui

ficara disponivel até o final de janeiro

**Comment by Mardoniosc** [comment]
> Estava utilizando essa API também, infelizmente acredito que possa ser por causa do heroku não ser mais gratuito como o colega disse.

Gostaria de ver a aplicação você publicou?

**Comment by Mardoniosc** [comment]
> Amigo, criei um app que consome sua API, e não está mais funcionando, tem previsão de retorno ou encerrou os serviço. Fiz app como exercício da minha faculdade.

Gostaria de ver a aplicação você publicou?

**Comment by gleitons** [comment]
> 



> > Estava utilizando essa API também, infelizmente acredito que possa ser por causa do heroku não ser mais gratuito como o colega disse.
> 
> Gostaria de ver a aplicação você publicou?

https://megadehoje.vercel.app/mega-sena
