### ISSUE TITLE
Curiosidade

### ISSUE THREAD

**Issue by JorgeOrnelasSouza** [guto-alves/loterias-api#18]
Desculpe a minha pergunta de leigo, mas eu posso jogar esses dados numa interface gráfica, amigável e simples?

**Comment by guto-alves** [comment]
Olá Jorge! Sim é possível, qualquer aplicação consegue consumir os dados da API.

Segue alguns links que podem te ajudar com isso:
https://www.youtube.com/watch?v=vYlz3SmNXQQ&t=574s
https://www.devmedia.com.br/trabalhando-com-api/
https://learn.microsoft.com/pt-br/dotnet/architecture/modern-web-apps-azure/common-client-side-web-technologies
