### ISSUE TITLE
Parabéns

### ISSUE THREAD

**Issue by habreu** [guto-alves/loterias-api#19]
Guto, Bom dia!!

Primeiramente eu gostaria de lhe parabenizar pela api super bem desenvolvida um excelente trabalho!

Outro ponto hoje quando fui autualizar a mesma, notei que não esão trazendo os jogos de ontem. Será que houve algum problema com a Caixa?

**Comment by AlissonHanael** [comment]
Habreu, eu li o código e ele não está consumindo os dados no site da caixa e sim do sorte online, porém o site Sorte online teve uma atualização que teve mudanças no nome das classes e em alguns detalhes de estrutura do site logo ele não está rodando pois ele não encontra as classes requisitadas. Estou aguardando correção também.
