### ISSUE TITLE
Atualização no SorteOnline

### ISSUE THREAD

**Issue by AlissonHanael** [guto-alves/loterias-api#20]
Olá, vi que você consome os dados do site Sorte Online, porém recentemente eles tiveram uma atualização no site que ocasionou mudanças no nome das classes que você colocou, exemplo:

Na classe consumer.java: 
 Integer.valueOf(resultElement.getElementsByClass("header-resultados__nro-concurso").text()));
ela agora deve ser 
Integer.valueOf(resultElement.getElementsByClass("MuiTypography-root MuiTypography-body1 css-1oj331g").text())); 
E ainda vai ter q usar alguma função para separar a data do numero do concurso que estão juntos agora.

**Comment by guto-alves** [comment]
Obrigado por reportar. Atualizei a API e já está funcionando novamente.
