### ISSUE TITLE
Duvida problema de atualização dos resultados

### ISSUE THREAD

**Issue by tarciziovn** [guto-alves/loterias-api#21]
Primeiramente parabéns pela API... gostaria de saber o que houve que os resultados não vem sendo atualizados? A API da mega-sena mesmo eu vi que o último resultado é de 4 concursos atrás: 29/07/2023.
O que aconteceu?

**Comment by AlissonHanael** [comment]
@tarciziovn boa tarde, acompanha as Issues anteriores. Já abri uma Issue dessa.

**Comment by guto-alves** [comment]
#20
