### ISSUE TITLE
Atualização da API

### ISSUE THREAD

**Issue by ThiagoPetry** [guto-alves/loterias-api#23]
Boa noite
Percebi que a partir do concurso 2900 a API não retorna mais os dados. Será avaliado e corrigido?
Ex: https://loteriascaixa-api.herokuapp.com/api/lotofacil/2900

**Comment by guto-alves** [comment]
Olá @ThiagoPetry 
[O concurso número 2900 está marcado para 09/09/2023, às 20h](https://jc.ne10.uol.com.br/blogs/torcedor/2023/09/15584886-resultado-da-lotofacil-2900-resultado-da-lotofacio-da-idependencia-vai-ser-sorteano-neste-sabado-02-09-caixa-alterou-data-entenda.html#:~:text=A%20Caixa%20Econ%C3%B4mica%20Federal%20N%C3%83O,de%20R%24%20R%24200%20milh%C3%B5es.)

**Comment by ThiagoPetry** [comment]
Puts, n percebi que pararam no dia 25/08 kkkk, mals
