### ISSUE TITLE
mesSorte vazio no Dia de Sorte

### ISSUE THREAD

**Issue by g-pg** [guto-alves/loterias-api#26]
A prop "mesSorte" está voltando apenas uma string vazia nos últimos resultados dos sorteios do Dia de Sorte.

Eu faria um PR, mas dei uma olhada nos seletores e eles nem existem no sorteonline.com.br, então imagino que este repositório esteja completamente diferente da produção hehe

Também notei que o mesSorte era o número do mês no início da API, e depois passou a ser o nome. Seria legal padronizar isso para os resultados passados.

**Comment by guto-alves** [comment]
Obrigado pelo report, @g-pg! 

Fiz as seguintes correções:
- Corrigido o bug dos campos "mesSorte" e "timeCoracao" vazios.
- Padronização do campo "mesSorte" (utilizado pela loteria Dia de Sorte) para conter o nome do mês por extenso (e não o número).
- O código do repositório alinhado com a prod.

**Comment by g-pg** [comment]
@guto-alves Muito obrigado!
