### ISSUE TITLE
Blocked by CORS policy: 'No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by pcteilor** [guto-alves/loterias-api#3]
Estava desenvolvendo localmente com a API mas quando  executo o GET para receber os dados recebo esse código de erro.

```
Access to XMLHttpRequest at 'https://loterias-api-gutotech.herokuapp.com/api/v0/megasena/latest' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET https://loterias-api-gutotech.herokuapp.com/api/v0/megasena/latest net::ERR_FAILED 200
```

Está faltando algo na minha requisição?
Estou usando React e Axios.

**Comment by guto-alves** [comment]
Eu acabei de desabilitar o CORS da aplicação, você pode tentar novamente e ver se não apresenta mais esse erro?   

Apenas uma observação: a API que você está acessando não está mais recebendo atualizações porque foi substituída pela ```https://loterias-gutotech.herokuapp.com```.
Eu atualizei recentemente o [README.md](https://github.com/guto-alves/loterias-api/blob/main/README.md#exemplos-de-retorno) com os novos exemplos de retorno. Por enquanto as duas estão no ar, mas em breve deixarei só a atual.

URL da API ATUAL: https://loterias-gutotech.herokuapp.com
~~DESCONTINUADA: https://loterias-api-gutotech.herokuapp.com~~

**Comment by pcteilor** [comment]
Ontem eu testei e tinha funcionado a requisição mas estava vendo se estava tudo vindo corretamente. 
Hoje aparentemente saiu do ar a API.

**Comment by guto-alves** [comment]
Desculpe pelo transtorno. A API foi movida para https://loteriascaixa-api.herokuapp.com. 
Veja o [README.md](https://github.com/guto-alves/loterias-api#exemplos-de-retorno) com os novos exemplos de utilização da API. 

Qualquer dúvida estou à disposição!
