### ISSUE TITLE
Link para doacao pelo pagseguro fora do ar.

### ISSUE THREAD

**Issue by cleissonalves** [guto-alves/loterias-api#36]
Olá, estou desenvolvendo uma aplicacao cli em rust que utiliza a api.

Gostaria de contribuir para a manutencao da hospedagem, porém o link https://pag.ae/7ZqNrvmsK redireciona para uma página de erro com a mensagem:

> Funcionalidade desativada. Entre em contato com o vendedor para avaliar outro meio para realizar o pagamento.

**Comment by guto-alves** [comment]
Olá, @cleissonalves!

Obrigado por avisar! Segundo o PagBank, [o recurso de Doação foi descontinuado em 11 de novembro de 2024](https://faq.pagbank.com.br/duvida/o-que-e-o-botao-de-doacao/2214#rmcl).
Considerando as alternativas disponibilizadas por eles, criei um QR CODE PIX  e um novo Link de Pagamento para as doações.

Atualizei o [README.md](https://github.com/guto-alves/loterias-api?tab=readme-ov-file#doa%C3%A7%C3%A3o-importante) com as novas opções.

O commit 08d52d858d55a1860fdebd2e512751ed999d6f98 resolveu o problema.
