### ISSUE TITLE
problema 500

### ISSUE THREAD

**Issue by guigs1997** [guto-alves/loterias-api#4]
Bom dia, não sei se o problema é na api desenvolvida (mto boa por sinal) mas estou tentando consultá-la em 27/11/2021 as 11:11 da manhã no link https://loterias-gutotech.herokuapp.com/api/v0/megasena/1 e recebo o seguinte erro:

<!DOCTYPE html>
<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<title>No such app</title>
	<style media="screen">
		html,
		body,
		iframe {
			margin: 0;
			padding: 0;
		}

		html,
		body {
			height: 100%;
			overflow: hidden;
		}

		iframe {
			width: 100%;
			height: 100%;
			border: 0;
		}
	</style>
</head>

<body>
	<iframe src="//www.herokucdn.com/error-pages/no-such-app.html"></iframe>
</body>

</html>

**Comment by guto-alves** [comment]
Desculpe pelo transtorno. A API foi movida para https://loteriascaixa-api.herokuapp.com. 
Veja o [README.md](https://github.com/guto-alves/loterias-api#exemplos-de-retorno) com os novos exemplos de utilização da API.

Sua tentativa ~~https://loterias-gutotech.herokuapp.com/api/v0/megasena/1~~ pode ser realizada agora com:
https://loteriascaixa-api.herokuapp.com/api/mega-sena/1
