### ISSUE TITLE
Serviço Indisponível

### ISSUE THREAD

**Issue by caldasluan** [guto-alves/loterias-api#6]
Ao tentar acessar a API, o Heroku está retornando erro.
![IMG_20211229_102047](https://user-images.githubusercontent.com/20692539/147666706-52518bce-0333-4cc5-900c-84cf8a9c3b80.jpg)

**Comment by vcavichini** [comment]
same here :-(

**Comment by guto-alves** [comment]
Olá, pessoal! Muito obrigado por reportar o problema, acabei de resolver isso. Obrigado pela paciência e desculpe o transtorno.
